#' Consolidate concentration data
#'
#' @param directory The directory from which to load the data.
#' Default: c("EGF", "oxygen")
#' @return A single list of data frames, one for each element to plot.
#' @export

consolidateConcentrationData = function(directory = "") {
  files = list.files(directory, pattern = ".csv", full.names = FALSE)
  concentration =
    lapply(
      paste0(directory, "/", files),
      function(x) utils::read.csv(x, sep = ",")
    )
  concentration = do.call("rbind", Map(cbind,
    Time = sapply(stringr::str_split(files, pattern = "_"), `[`, 4),
    concentration
  ))

  concentration$Time =
    as.numeric(gsub(pattern = "t", replacement = "", concentration$Time))
  concentration = concentration[with(concentration, order(Time, i, j)), ]

  return(concentration)
}

#' Plot concentrations of elements of interest
#'
#' @param data The input data,
#'  generated by \code{\link{consolidateConcentrationData}}.
#' @param directory The directory to which the plot should be saved.
#' @param to.plot Element to plot. Default: EGF.
#' @param plot.title The plot title.
#' @param plot.subtitle The plot subtitle.
#' @param in.width Width in inches.
#' @param in.height Height in inches.
#'
#' @return A list of with heatmap plots of concentrations per i,j.
#' @export
#'
#'


plotConcentration = function(data,
                             directory = "",
                             filename = "concentrationPlots",
                             to.plot,
                             viridis_palette = "magma",
                             fill_direction = 1,
                             plot.title = " concentration",
                             in.width = 9,
                             in.height = 9) {
  data = data %>%
    select(Time, i, j, {{ to.plot }})
  p = data %>%
    ggplot(aes(x = i, y = j, fill = {{ to.plot }})) +
    geom_raster() +
    ggpubr::theme_pubr() +
    viridis::scale_fill_viridis(
      option = viridis_palette,
      breaks = round(seq(min(as.numeric(data[, 4])),
        max(as.numeric(data[, 4])),
        length = 3), digits = 2),
      labels = formatC(seq(min(as.numeric(data[, 4])),
        max(as.numeric(data[, 4])),
        length = 3),
      format = "e", digits = 2), direction = fill_direction) +
    facet_wrap("Time") +
    theme(
      axis.text.x = element_blank(), axis.text.y = element_blank(),
      axis.line = element_blank(), axis.ticks = element_blank()) +
    ggtitle(plot.title)

  plot(p)

  ggsave(paste0(directory, filename, ".png"),
    p,
    width = in.width, height = in.height, dpi = 400
  )

  return(p)
}
