#' Consolidate concentration data
#'
#' @param directory The directory from which to load the data.
#' @param to.plot Elements of interest to plot later.
#' Default: c("EGF", "oxygen")
#' @return A single list of data frames, one for each element to plot.
#' @export

consolidateConcentrationData = function(directory = "",
                                        to.plot = c("EGF", "oxygen")) {
  files = list.files(directory, pattern = ".csv", full.names = FALSE)
  concentration =
    lapply(paste0(directory, "/", files), function(x) read.csv(x, sep = ","))
  concentration = do.call("rbind", Map(cbind,
    Time = sapply(stringr::str_split(files, pattern = "_"), `[`, 4),
    concentration
  ))
  # for (element in to.plot) {
  #   concentration[, element] =
  #     # format to scientific notation to prevent misbehavior of plots
  #     as.numeric(concentration[, element], scientific = TRUE)
  # }
  concentration$Time =
    as.numeric(gsub(pattern = "t", replacement = "", concentration$Time))
  concentration = concentration[with(concentration, order(Time, i, j)), ]

  return(concentration)
}

#' Plot concentrations of elements of interest
#'
#' @param data The input data,
#'  generated by \code{\link{consolidateConcentrationData}}.
#' @param directory The directory to which the plot should be saved.
#' @param to.plot Element to plot. Default: EGF.
#' @param plot.title The plot title.
#' @param plot.subtitle The plot subtitle.
#' @param in.width Width in inches.
#' @param in.height Height in inches.
#'
#' @return A list of with heatmap plots of concentrations per i,j.
#' @export
#'
#'

plotConcentration = function(data,
                             directory = "",
                             filename = "concentrationPlots",
                             to.plot = "EGF",
                             plot.title = " concentration",
                             in.width = 9,
                             in.height = 9) {
  heatmap_list = list()
  legend_list = list()

    for (time in unique(data$Time)) {
      mat = data %>%
        dplyr::select(!c(setdiff(setdiff(
          colnames(data), c("Time", "i", "j")
        ), to.plot))) %>%
        pivot_wider(
          names_from = j, values_from = as.symbol(to.plot),
          id_expand = TRUE
        ) %>%
        filter(Time == time) %>%
        dplyr::select(!Time) %>%
        as.data.frame()

      rownames(mat) = mat$i
      mat = mat[-1]

      mat = matrix(as.numeric(unlist(mat)), nrow = nrow(mat))

      rownames(mat) = c(0:(nrow(mat) - 1))
      colnames(mat) = c(0:(ncol(mat) - 1))

      if (length(unique(seq(min(as.numeric(data[, to.plot])),
        max(as.numeric(data[, to.plot])),
        length = 3
      ))) < 2) {
        message(
          "Warning: min() and max() values for ", to.plot, " at time ",
          time, " are identical. Not saving plot."
        )
      } else {
        color = circlize::colorRamp2(seq(min(as.numeric(data[, to.plot])),
          max(as.numeric(data[, to.plot])),
          length = 3
        ), c("#188FA7", "#EEEEEE", "#EC4E20"), space = "RGB")
        heatmap_list[[paste0(to.plot, "_", time)]] =
          grid::grid.grabExpr(ComplexHeatmap::draw(ComplexHeatmap::Heatmap(
            mat,
            cluster_rows = F,
            cluster_columns = F,
            na_col = "white",
            row_order = order(as.numeric(rownames(mat)), decreasing = TRUE),
            row_names_side = "left",
            column_labels = rep("",ncol(mat)),
            row_labels = rep("",ncol(mat)),
            rect_gp = grid::gpar(col = "white", lwd = 2),
            col = color,
            border = FALSE,
            column_title = paste0("Time = ", time),
            column_title_side = "bottom",
            show_heatmap_legend = FALSE,
            width = ncol(mat) * unit(1.5, "mm"), # to create square grid
            height = ncol(mat) * unit(1.5, "mm"),
          )))

        if (time == max(data$Time)) {
          # drawing only at last time per element plotted to
          # facilitate patchwork alignment
          legend_list[[paste0(to.plot, "_", time)]] =
            grid::grid.grabExpr(ComplexHeatmap::draw(ComplexHeatmap::Legend(
              at = seq(min(as.numeric(data[, to.plot])),
                               max(as.numeric(data[, to.plot])),
                               length = 3),
              labels = formatC(seq(min(as.numeric(data[, to.plot])),
                                   max(as.numeric(data[, to.plot])),
                                   length = 3), 
                               format = "e",digits = 2),
              title = to.plot, col_fun = color
            )))
        }
      }
    
  }
  if (!file.exists(directory)) {
    dir.create(directory)
  }
  p = patchwork::wrap_plots(c(heatmap_list, legend_list)) +
    patchwork::plot_annotation(
    title = paste0(to.plot, plot.title)
  ) 
  plot(p) # this won't be accurate, check printed version

  ggsave(paste0(directory,"/", filename, ".png"),
         p, width = in.width, height = in.height)

  return(p)
}
