#' Consolidate fate data
#'
#' @param directory The directory from which to load the data.
#' @param mutants.to.plot Mutants to plot in separate figures later.
#' @return A single list of data frames, one for each element to plot.
#' @export
#'
consolidateFateData = function(directory = "",
                               mutants.to.plot = c(
                                 "EGFR+", "p53-PTEN-",
                                 "EGFR+p53-PTEN-", "WT"
                               )) {
  files = list.files(directory, pattern = ".csv", full.names = FALSE)
  
  df = read.csv(paste0(directory, "/", files),check.names = FALSE)  %>% 
    rename(timepoint = `time point`) %>% 
    pivot_longer(!timepoint, values_to = 'count') %>% 
    separate(name, sep = '_', into = c("mutant", "fate"), extra = 'merge') %>%
    na.omit() %>%
    pivot_wider(names_from = c( fate), values_from = count) %>%
    group_by(mutant) %>%
    mutate(apoptosis_cumulative = cumsum(apoptosis)) %>%
    pivot_longer(cols = !c(timepoint, mutant), names_to = "Fate", values_to = "count")
  
  
  return(df)
}

#' Plot summary of fate of mutants of interest in stacked area
#'
#' @param data The input data,
#'  generated by \code{\link{consolidateNodeStatusData}}.
#' @param directory The directory to which the plot should be saved.
#' @param plot.title The plot title.
#' @param plot.subtitle The plot subtitle.
#' @param in.width Width in inches.
#' @param in.height Height in inches.
#'
#' @return A list of stacked area plots of number of cells reaching
#' fate decisions per timepoint per mutant.
#' @export
#'
#'

plotFate = function(data,
                    directory = "",
                    filename = "nodeStatusPlots",
                    apoptosis.cumulative = TRUE,
                    plot.title = "Number of cells reaching each fate",
                    plot.subtitle = "Per timepoint and mutant",
                    in.width = 9,
                    in.height = 7) {

  # Apoptosis or Apoptosis_cumulative
  if (apoptosis.cumulative == TRUE) {
    data = data %>%
      dplyr::filter(Fate != "apoptosis")
  } else {
    data = data %>%
      dplyr::filter(Fate != "apoptosis_cumulative")
  }

  p = data %>%
    dplyr::mutate(Fate = relevel(as.factor(Fate), ref = "no_fate_reached")) %>%
    ggplot(., aes(x = timepoint, y = count, fill = Fate, color = Fate)) +
    geom_area(alpha = 0.8, size = .1) +
    viridis::scale_fill_viridis(discrete = T) +
    viridis::scale_color_viridis(discrete = T) +
    xlab("Time point") +
    ylab("Cell count") + 
    ggtitle(label = plot.title, subtitle = plot.subtitle)

  p = ggpubr::facet(p + theme_pubr(), facet.by = "mutant",
        #short.panel.labs = FALSE,   
        panel.labs.background = list(fill = "white", color = "black")
  )
  
  if (!file.exists(directory)) {
    dir.create(directory)
  }
  ggsave(paste0(directory, filename, ".png"),
    p,
    width = in.width, height = in.height
  )

  return(p)
}

# TODO
# there are negative no_decision values
