#' Consolidate fate data
#'
#' @param directory The directory from which to load the data.
#' @return A single dataframe in long format.
#' @export
#'
consolidateFateData = function(directory = "") {
  files = list.files(directory, pattern = ".csv", full.names = FALSE)

  df_list = lapply(files,function(x){
    utils::read.csv(paste0(directory, "/", x), check.names = FALSE)
  })
  names(df_list) = files
  df =  do.call(rbind,  df_list) %>%
    dplyr::group_by(`time point`) %>%
    dplyr::summarise(across(where(is.numeric), mean)) %>%
    rename(timepoint = `time point`) %>%
    tidyr::pivot_longer(!timepoint, values_to = "count") %>%
    separate(name, sep = "_", into = c("mutant", "fate"), extra = "merge") %>%
    stats::na.omit() %>%
    tidyr::pivot_wider(names_from = c(fate), values_from = count) %>%
    group_by(mutant) %>%
    mutate(apoptosis_cumulative = cumsum(apoptosis)) %>%
    tidyr::pivot_longer(
      cols = !c(timepoint, mutant),
      names_to = "Fate", values_to = "count"
    )


  return(df)
}

#' Plot summary of fate of mutants of interest in stacked area
#'
#' @param data The input data,
#'  generated by \code{\link{consolidateFateData}}.
#' @param directory The directory to which the plot should be saved.
#' @param plot.title The plot title.
#' @param plot.subtitle The plot subtitle.
#' @param in.width Width in inches.
#' @param in.height Height in inches.
#'
#' @return A list of stacked area plots of number of cells reaching
#' fate decisions per timepoint per mutant.
#' @export
#'
#'

plotFate = function(data,
                    directory = "",
                    filename = "nodeStatusPlots",
                    apoptosis.cumulative = TRUE,
                    plot.title = "Number of cells reaching each fate",
                    plot.subtitle = "Per timepoint and mutant",
                    in.width = 9,
                    in.height = 7,
                    descending = F) {

  # Apoptosis or Apoptosis_cumulative
  if (apoptosis.cumulative == TRUE) {
    data = data %>%
      dplyr::filter(Fate != "apoptosis")
  } else {
    data = data %>%
      dplyr::filter(Fate != "apoptosis_cumulative")
  }

  p = data %>%
    dplyr::mutate(Fate = forcats::fct_reorder(Fate, count, .desc = descending)) %>%
    ggplot(., aes(x = timepoint, y = count, fill = Fate, color = Fate)) +
    geom_area(alpha = 0.8, size = .1) +
    viridis::scale_fill_viridis(discrete = T) +
    viridis::scale_color_viridis(discrete = T) +
    xlab("Time point") +
    ylab("Cell count") +
    ggtitle(label = plot.title, subtitle = plot.subtitle)

  p = ggpubr::facet(p + ggpubr::theme_pubr(),
    facet.by = "mutant",
    panel.labs.background = list(fill = "white", color = "black")
  )

  if (!file.exists(directory)) {
    dir.create(directory)
  }
  ggsave(paste0(directory, filename, ".png"),
    p, width = in.width, height = in.height)

  return(p)
}
