#' Consolidate node status data
#'
#' @param directory The directory from which to load the data.
#' @param mutants.to.plot Mutants to plot in separate figures later.
#' @return A single list of data frames, one for each element to plot.
#' @export
#' 
consolidateNodeStatusData = function(directory = "",
                                        mutants.to.plot = c( "mutA", "mutB",
                                                             "mutC","WT")) {
  
  files = list.files(directory, pattern = ".csv", full.names = FALSE)
  df = read.csv(paste0(directory, "/", files)) %>%
    dplyr::relocate(cell.count, .after = WT)
  df_list = list()
  for(mutant in to.plot){
    df_list[[mutant]] = df[c("time.point",grep(mutant, colnames(df), 
                                               value = TRUE))]
    colnames(df_list[[mutant]])[grep("expressing",
                                     colnames(df_list[[mutant]]))] = 
      sapply(stringr::str_split(colnames(df_list[[mutant]])[grep("expressing",
                        colnames(df_list[[mutant]]))], pattern = "\\."),`[`, 3)
    df_list[[mutant]] = df_list[[mutant]] %>% 
      na.omit() %>%
      dplyr::mutate(Apoptosis_cumulative = cumsum(Apoptosis)) %>%
      dplyr::mutate(to_substract = as.numeric(rowSums(.[3:(ncol(.)-1)]))) 
    df_list[[mutant]]["No_decision"] = df_list[[mutant]][mutant] - df_list[[mutant]]["to_substract"]
    df_list[[mutant]] = df_list[[mutant]] %>%
      pivot_longer(cols = !c(time.point,  as.symbol(mutant),to_substract), 
                   names_to = "Fate", values_to = "Cells") %>%
      dplyr::mutate(Mutant = mutant)
    df_list[[mutant]]$Total_cells = df_list[[mutant]][[mutant]]
    df_list[[mutant]] = df_list[[mutant]] %>% 
      dplyr::select(time.point,Total_cells,Mutant,Fate,Cells)
    
  }
  
  df = do.call("rbind", df_list)
  
  return(df)
}

#' Plot summary of status (fate) of mutants of interest in stacked area
#'
#' @param data The input data,
#'  generated by \code{\link{consolidateNodeStatusData}}.
#' @param directory The directory to which the plot should be saved.
#' @param plot.title The plot title.
#' @param plot.subtitle The plot subtitle.
#' @param in.width Width in inches.
#' @param in.height Height in inches.
#'
#' @return A list of stacked area plots of number of cells reaching  fate decisions per timepoint per mutant.
#' @export
#'
#'

plotStatus = function(data,
                             directory = "",
                             filename = "nodeStatusPlots", 
                             apoptosis.cumulative = TRUE,
                             plot.title = "Number of cells reaching each fate",
                             plot.subtitle = "Per timepoint and mutant",
                             in.width = 9,
                             in.height = 7) {
  
  # Apoptosis or Apoptosis_cumulative
  if(apoptosis.cumulative == TRUE){
    data = data %>% 
      dplyr::filter(Fate != "Apoptosis")
  } else{
    data = data %>% 
      dplyr::filter(Fate != "Apoptosis_cumulative")
  }
  
  p = data %>%
    dplyr::mutate(Fate = relevel(as.factor(Fate),ref = "No_decision")) %>%
  ggplot(., aes(x=time.point, y=Cells, fill=Fate, color = Fate)) + 
    geom_area(alpha=0.8 , size=.1) +
    viridis::scale_fill_viridis(discrete = T) +
    viridis::scale_color_viridis(discrete = T) +
    theme_minimal()+
    facet_wrap(facets = vars(Mutant)) + 
    xlab("Time point") + 
    ggtitle(label = plot.title, subtitle = plot.subtitle)
  
  if (!file.exists(directory)) {
    dir.create(directory)
  }
  ggsave(paste0(directory, filename, ".png"),
         p, width = in.width, height = in.height)
  
  return(p)
}


